azure:
  activeDirectory:
    base-uri: https://login.microsoftonline.com

    # 'Tenant ID' of your Azure AD instance - this value is a GUID
    tenant-id: value-here

    # 'Application ID URI' of app registration in Azure portal - this value typically starts with api://
    app-id-uri: value-here

    # This application is performing the OAuth role of only a resource server.
    application-type: resource_server
