# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "maven"
    directories:
      - "/access-protected-api"
      - "/access-protected-api-obo"
      - "/cli-access-protected-api"
      - "/protect-api"
      - "/webapp"
    schedule:
      interval: "weekly"
    labels:
      - "dependabot"
      - "dependencies"

  - package-ecosystem: "gradle"
    directories:
      - "/android-java"
      - "/android-kotlin"
    schedule:
      interval: "weekly"
    labels:
      - "dependabot"
      - "dependencies"
