azure:
  activeDirectory:
    base-uri: https://login.microsoftonline.com

    # 'Tenant ID' of your Azure AD instance - this value is a GUID
    tenant-id: value-here

    # 'Application ID URI' of app registration in Azure portal - this value typically starts with api://
    app-id-uri: value-here

    # 'Application (client) ID' of app registration in Azure portal - this value is a GUID
    client-id: value-here

    # Client secret 'Value' (not its ID) from 'Client secrets' in app registration in Azure portal
    client-secret: value-here

    authorization-clients:
      graph:
        authorization-grant-type: on_behalf_of
        scopes:
          - https://graph.microsoft.com/User.Read
