azure:
  activeDirectory:
    base-uri: https://login.microsoftonline.com

    # 'Tenant ID' of your Microsoft Entra instance - this value is a GUID
    tenant-id: Enter_the_Tenant_ID_Here

    # 'Application (client) ID' of app registration in the Microsoft Entra admin center - this value is a GUID
    client-id: Enter_the_Application_Id_Here

    # Client secret 'Value' (not its ID) from 'Client secrets' in app registration in the Microsoft Entra admin center
    client-secret: Enter_the_Client_Secret_Value_Here
    authorization-clients:
      graph:
        scopes:
          - https://graph.microsoft.com/User.Read
