azure:
  activeDirectory:
    base-uri: https://login.microsoftonline.com

    # 'Tenant ID' of your Azure AD instance - this value is a GUID
    tenant-id: 72f988bf-86f1-41af-91ab-2d7cd011db47

    # 'Application (client) ID' of app registration in Azure portal - this value is a GUID
    client-id: 982a029d-4a1e-4054-83a4-a76f5180f600

    # Client secret 'Value' (not its ID) from 'Client secrets' in app registration in Azure portal
    client-secret: nope
    authorization-clients:
      graph:
        scopes:
          - https://graph.microsoft.com/User.Read
